FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Code Challenge API

## Users Collection [/users]
### Create a New User [POST]
+ Request (application/json)
    
    + Headers

            Accept: application/json
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNDM0NDY3NDUxfQ.Or5WanRwK1WRqqf4oeIkAHRYgNyRssM3CCplZobxr4w
            
    + Body
    
            { 
                "email": "andre@orainteractive.com",
                "password": "test123",
                "confirm": "test123"
            }

+ Response 201 (application/json)

        {
          "success": true,
          "data": {
            "id": 1,
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNDM0NDY3NDUxfQ.Or5WanRwK1WRqqf4oeIkAHRYgNyRssM3CCplZobxr4w",
            "email": "andre@orainteractive.com",
            "name": "andre"
          }
        }
            
## User Login [/user/login]
### Login a User [POST]
+ Request (application/json)

    + Headers

            Accept: application/json
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNDM0NDY3NDUxfQ.Or5WanRwK1WRqqf4oeIkAHRYgNyRssM3CCplZobxr4w
            
    + Body
    
            {
                "email": "andre@orainteractive.com",
                "password": "test123"
            }

+ Response 200 (application/json)

        {
            "success": true,
            "data": {
                "id": 1,
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNDM0NDY3NDUxfQ.Or5WanRwK1WRqqf4oeIkAHRYgNyRssM3CCplZobxr4w",
                "email": "andre@orainteractive.com",
                "name": "andre"
            }
        }

## Current User [/user/me]
### Profile for Current User [GET]
+ Request (application/json)
    
    + Headers

            Accept: application/json
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNDM0NDY3NDUxfQ.Or5WanRwK1WRqqf4oeIkAHRYgNyRssM3CCplZobxr4w

+ Response 200 (application/json)

        {
            "success": true,
            "data": {
                "id": 1,
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNDM0NDY3NDUxfQ.Or5WanRwK1WRqqf4oeIkAHRYgNyRssM3CCplZobxr4w",
                "email": "andre@orainteractive.com",
                "name": "andre"
            }
        }

### Edit Current User [PUT]
+ Request (application/json)
    
    + Headers

            Accept: application/json
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNDM0NDY3NDUxfQ.Or5WanRwK1WRqqf4oeIkAHRYgNyRssM3CCplZobxr4w
    
    + Body

            {
                "email": "andre@orainteractive.com",
                "password": "test123"
            }

+ Response 201 (application/json)

        {
            "success": true,
            "data": {
                "id": 1,
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNDM0NDY3NDUxfQ.Or5WanRwK1WRqqf4oeIkAHRYgNyRssM3CCplZobxr4w",
                "email": "andre@orainteractive.com"
            }
        }

## Chats Collection [/chats]
### List Chats [GET]
+ Request (application/json)
    
    + Headers

            Accept: application/json
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNDM0NDY3NDUxfQ.Or5WanRwK1WRqqf4oeIkAHRYgNyRssM3CCplZobxr4w
            

+ Response 201 (application/json)

        {
            "success": true,
            "data": [{
                "id": 1,
                "user_id": 1,
                "name": "A Chat"
            },
            {
              "id": 2,
              "user_id": 1,
              "name": "A Chat 2"
            }],
            "pagination": {
                "page_count": 1,
                "current_page": 1,
                "has_next_page": false,
                "has_prev_page": false,
                "count": 1,
                "limit": null
            }
        }

### Create a New Chat [POST]
+ Request (application/json)
    
    + Headers

            Accept: application/json
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNDM0NDY3NDUxfQ.Or5WanRwK1WRqqf4oeIkAHRYgNyRssM3CCplZobxr4w
            
    + Body
    
            { 
                "email": "andre@orainteractive.com",
                "password": "test123",
                "confirm": "test123"
            }

+ Response 201 (application/json)

        {
          "success": true,
          "data": {
            "id": 1,
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNDM0NDY3NDUxfQ.Or5WanRwK1WRqqf4oeIkAHRYgNyRssM3CCplZobxr4w",
            "email": "andre@orainteractive.com",
            "name": "andre"
          }
        }